// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hturizvlqoiulqdlbdjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dXJpenZscW9pdWxxZGxiZGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzQ0NzQsImV4cCI6MjA2MzY1MDQ3NH0.YHYp7gITqhR8yNK1i0Gz0UPKsrjhMNxjtYTwap7HCsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);